# Generated by Django 3.0.4 on 2020-03-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '역할', 'verbose_name_plural': '역할'},
        ),
    ]
