# Generated by Django 3.0.4 on 2020-03-31 07:46

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveIntegerField(verbose_name='챕터')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('description', models.CharField(max_length=500, verbose_name='설명')),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), max_length=3, size=None, verbose_name='카데고리')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='disliked_works', related_query_name='disliked_work', to=settings.AUTH_USER_MODEL, verbose_name='싫어요')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_works', related_query_name='liked_work', to=settings.AUTH_USER_MODEL, verbose_name='좋아요')),
            ],
        ),
    ]
