# Generated by Django 3.0.4 on 2020-03-31 08:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20200331_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(1, 'romance'), (2, 'life'), (3, 'fun'), (4, 'fantasy'), (5, 'action'), (6, 'drama'), (7, 'thrill'), (8, 'history'), (9, 'sports')]), size=3, verbose_name='카테고리'),
        ),
    ]
