# Generated by Django 3.0.4 on 2020-03-31 08:39

from django.db import migrations, models
import django.db.models.deletion
import work.models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20200331_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='images',
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=work.models.get_uuid_artwork_image_url)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Artwork')),
            ],
            options={
                'verbose_name': '작화 이미지',
                'verbose_name_plural': '작화 이미지',
            },
        ),
    ]
